### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by joetcochran** [AndrewMcCrary/Senior-Design#1]
Initial thoughts include:
For personal use, no material regulatory impact to worry about
"thousands of trades per second" - i admire the ambition
does the api you want to use for the data streaming and trade execution provide for some kind of "paper money" 

https://www.webull.com/paper-trading?source=paper-trading-gl-search-pc&gad_source=1&gclid=Cj0KCQjwveK4BhD4ARIsAKy6pMJRSUKoljImMKawMvs32wGLmJx46XNZeVruUJLj0WUfrUPMPSobWV0aAvqSEALw_wcB

https://www.schwab.com/trading/thinkorswim/paper-trading?src=SEM&ef_id=Cj0KCQjwveK4BhD4ARIsAKy6pMI8xVbUnVn4OZIMPpyicmExcztCV94CFpXl5csnwxPngNolX9tO76EaArOtEALw_wcB:G:s&s_kwcid=AL!5158!3!677331202289!e!!g!!papermoney%20thinkorswim!20657279659!154195940323&keywordid=kwd-321789238008&gad_source=1&gclid=Cj0KCQjwveK4BhD4ARIsAKy6pMI8xVbUnVn4OZIMPpyicmExcztCV94CFpXl5csnwxPngNolX9tO76EaArOtEALw_wcB

**Comment by AndrewMcCrary** [comment]
@joetcochran Yeah, alpaca is the primary brokerage that I'm looking at, but I would like support for multiple.  This shouldn't be too difficult if the interface for placing orders is abstracted away.  Although, paper trading is not too difficult to emulate so that is an alternative option.

To clarify, "thousands of trades per second" is referencing the data that the application will be ingesting, not how many trades will be placed.  I don't have an ethernet cable attached to the NYSE, so arbitrage would be difficult.
